### ISSUE TITLE
irr crashes on Rails 2.3.8

### ISSUE THREAD

**Issue by c-castillo** [wkranec/finance#11]
Me again. I have a strange performance issue on Ruby 1.9.3p194 with Rails 2.3.8. When I run a simple calculation of irb to limited set of cashflows on irb, it works fine.
But when i'm running ./script/console or in the app itself, .irr takes infinutum time and crashes the app server.

In the Rails app, I include the gem in the Gemfile and include the finance Module on the class.

Thanks in advance.

**Comment by gumatias** [comment]
@c-castillo I had no luck with using `Flt::DecNum`. I know this has been AWHILE, but I'm very curious if you've dealt with a similar performance issue and tried a different approach. thanks!
